name: Build Docker

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build & Push Image
      run: |
        echo "DockerHubကSecret" | docker login -u "DockerHubကName" --password-stdin
        docker image build -t "DockerHubကName"/fclone:latest .
        docker push "DockerHubကName"/fclone:latest
